require 'dotenv/load'
require 'json'
require 'net/http'
require 'rest-client'
require 'rufus-scheduler'
require 'sequel'
require 'telegram/bot'
require './db/db_setup'
require './models/rating'
require './models/schedule'
require './models/task'
require './models/user'
require './lib/listener'
require './lib/parser'
require './lib/pathfinder'
require './lib/ratinger'
require './lib/responder'
require './lib/sender'
require './lib/tasksheduler'

listener = Listener.new
listener.run
